FROM fedora:latest

# Install PCP and Workload packages
RUN dnf install -y --setopt=tsflags=nodocs \
	pcp-zeroconf pcp-pmda-openmetrics pcp-pmda-denki \
	openssl sysbench \
	&& \
    dnf clean all && \
    touch /var/lib/pcp/pmdas/{openmetrics,denki}/.NeedInstall

# is this even needed??
RUN systemctl enable pmcd pmie pmlogger pmproxy

CMD ["/usr/sbin/init"]
