FROM fedora:latest

# Install PCP and Workload packages
RUN dnf install -y --setopt=tsflags=nodocs \
	pcp-zeroconf pcp-pmda-openmetrics pcp-pmda-denki pcp-pdma-lmsensors \
	openssl sysbench \
        git jq \
	&& \
    dnf clean all && \
    touch /var/lib/pcp/pmdas/{openmetrics,denki,lmsensors}/.NeedInstall

# Doesn't pcp-zeroconf already do this?
RUN systemctl enable pmcd pmie pmlogger pmproxy

CMD ["/usr/sbin/init"]
