{
 "title": "Demo PC2025",
 "time": { "from": "2025-03-17T14:33:12.440Z", "to": "2025-03-17T14:53:15.279Z" },
 "panels": [
  {
   "title": "Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "denki.rapl",
     "legendFormat": "$metric[$instance]",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.RFchassis.watts",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "CPU Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kernel.all.cpu.user",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "kernel.all.cpu.sys",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Workload States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "openmetrics.workload.started",
     "legendFormat": "Started",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.workload.iteration",
     "legendFormat": "Iteration Number",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Workload Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "openmetrics.workload.throughput",
     "legendFormat": "Throughput",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.workload.latency",
     "legendFormat": "Latency",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  }
 ]
}