FROM fedora:40

# Install PCP and Workload packages
RUN dnf install -y --setopt=tsflags=nodocs \
	pcp-zeroconf pcp-pmda-openmetrics pcp-pmda-denki \
#	openssl sysbench \
	sysbench awk \
#        git jq \
	&& \
    dnf clean all && \
    touch /var/lib/pcp/pmdas/{openmetrics,denki}/.NeedInstall

# Doesn't pcp-zeroconf already do this?
RUN systemctl enable pmcd pmie pmlogger pmproxy

# Configure RFchassis openmetrics scripting
COPY RFvars.cfg /var/lib/pcp/pmdas/openmetrics/config.d/.
COPY RFchassis.sh /var/lib/pcp/pmdas/openmetrics/config.d/.
RUN chmod 755 /var/lib/pcp/pmdas/openmetrics/config.d/RFchassis.sh

# Configure Workload openmetrics scripting
COPY openmetrics_workload.txt /tmp/.
COPY workload.url /var/lib/pcp/pmdas/openmetrics/config.d/.
RUN systemctl restart pmcd

CMD ["/usr/sbin/init"]

