{
 "title": "COPY PCP Archive Analysis",
 "time": { "from": "2025-03-17T14:32:24.768Z", "to": "2025-03-17T14:50:06.191Z" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "performancecopilot-valkey-datasource"
   },
   { "name": "host", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Power Usage (Watts)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "denki.rapl{hostname == \"$host\"}",
     "legendFormat": "$metric[$instance]",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.RFchassis.watts",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Workload Results",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "yaxes": [
    { "format": "eps" }
   ],
   "targets": [
    {
     "expr": "openmetrics.workload.throughput{hostname == \"$host\"}",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.workload.latency{hostname == \"$host\"}",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "CPU busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kernel.all.cpu.user{hostname == \"$host\"}",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "kernel.all.cpu.sys",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Workload States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "yaxes": [
    { "format": "bool" }
   ],
   "targets": [
    {
     "expr": "openmetrics.workload.started{hostname == \"$host\"}",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.workload.iteration",
     "legendFormat": "$metric",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  }
 ]
}